// <auto-generated />
using System;
using Hamsterdagis;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hamsterdagis.Migrations
{
    [DbContext(typeof(HamsterDBContext))]
    partial class HamsterDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hamsterdagis.Cage", b =>
                {
                    b.Property<int>("CageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("CageId");

                    b.ToTable("Cages");
                });

            modelBuilder.Entity("Hamsterdagis.ExerciseArea", b =>
                {
                    b.Property<int>("ExerciseAreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ExerciseAreaId");

                    b.ToTable("ExerciseArea");
                });

            modelBuilder.Entity("Hamsterdagis.Hamster", b =>
                {
                    b.Property<int>("HamsterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CageId")
                        .HasColumnType("int");

                    b.Property<int?>("ExerciseAreaId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("LastTimeExercised")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HamsterId");

                    b.HasIndex("CageId");

                    b.HasIndex("ExerciseAreaId");

                    b.ToTable("Hamsters");
                });

            modelBuilder.Entity("Hamsterdagis.Hamster", b =>
                {
                    b.HasOne("Hamsterdagis.Cage", "Cage")
                        .WithMany("HamsterId")
                        .HasForeignKey("CageId");

                    b.HasOne("Hamsterdagis.ExerciseArea", null)
                        .WithMany("Hamsters")
                        .HasForeignKey("ExerciseAreaId");

                    b.Navigation("Cage");
                });

            modelBuilder.Entity("Hamsterdagis.Cage", b =>
                {
                    b.Navigation("HamsterId");
                });

            modelBuilder.Entity("Hamsterdagis.ExerciseArea", b =>
                {
                    b.Navigation("Hamsters");
                });
#pragma warning restore 612, 618
        }
    }
}
